### ISSUE TITLE
Sequelize 3.0.0 breaks master

### ISSUE THREAD

**Issue by bp323** [fronteerio/grasshopper#108]
The Sequelize package has been updated to 3.0.0 and breaks the current master branch. https://www.npmjs.com/package/sequelize

**Comment by simong** [comment]
Fixed in https://github.com/fronteerio/grasshopper/commit/b1360cfcd926ffa5f8b6f0539767c650189d7fcb

**Comment by simong** [comment]
I didn't mean to close this. Is latest master working for you again?

**Comment by bp323** [comment]
Working now, thanks!

**Comment by simong** [comment]
Cool, thanks for reporting. Hopefully they've gotten all their breaking changes out of the way now :/
