### ISSUE TITLE
Implement OAuth

### ISSUE THREAD

**Issue by simong** [fronteerio/grasshopper#67]
In order to make it easier for external applications and developers to interact with the Timetable REST APIs, the following types of OAuth support should be added:

 * 2-legged OAuth, allowing for server-to-server communication
 * 3-legged OAuth, allowing for third-party services to interact with the system on behalf of a user

2-legged OAuth can be used for integration between Timetable and a different trusted system. An example of such integration would be an integration of the Timetable data into Moodle courses.
3-legged OAuth will provided external application developers a way to ask permission to interact with the user's calendar on their behalf.

The implementation of OAuth scopes is excluded from this package of work. Therefore, a user will be able to use the full REST API once an OAuth access token has been obtained. Users will be able to revoke a third-party integration at any time.

**Comment by mrvisser** [comment]
So I'm thinking at least to start we'll need an OauthClient API where client applications can be CRUDded in the system.

From a global perspective, 2 legged authentication can be achieved by creating an access token for an application from the administrative application. We should try and limit the access of what that token can do to a user that the client will be impersonating (similar to 2-legged-oauth proposal for OAE)

From a user perspective, there would be endpoints where you can create an access token for an application that is registered in the system which effectively grants the holder of that token access to perform operations on behalf of the user.

Does that sound about right?

**Comment by mrvisser** [comment]
I might need clarification on what this means across tenants and apps -- is tenant actually a thing in Grasshopper? I see a Tenants API but I'm having trouble seeing how they fit in. Do many apps belong to a tenant, or vice versa?

**Comment by mrvisser** [comment]
Just clarified with @simong , everything is app-level. So:

* App admins are responsible for creating the authorized clients
* App admins are responsible for creating 2LO tokens and assigning to a user
* Users can run through a 3LO workflow with those clients

When apps are rolled over, OAuth clients have to be recreated

**Comment by mrvisser** [comment]
PR @ #100
