### ISSUE TITLE
Managing application administrators

### ISSUE THREAD

**Issue by simong** [fronteerio/grasshopper#69]
A set of REST APIs will be made available through which the administrators for an application can be managed. These REST aPIs can be used to make regular users application administrators or revoke the administrator status of an existing application administrator. The manage application administrator REST APIs will only be available to application and global administrators.

**Comment by simong** [comment]
There's already:
 - `/api/apps/:id/admins` which lists all the application administrators for an application
 - `/api/user/:id/admin` to elevate/demote a user's admin status

Similarly, for global administrators there is:
 - /api/admins to create a new global admin or get all the global admins
 - /api/admins/:id to update a specific admin

It looks like we only need an endpoint to delete a specific global admin

**Comment by simong** [comment]
Assigning to @mrvisser as this seems like a nice chunk of work

**Comment by mrvisser** [comment]
You're a nice chunk of work

**Comment by mrvisser** [comment]
> It looks like we only need an endpoint to delete a specific global admin

@simong do you mean demote?

**Comment by simong** [comment]
No, I think they can be deleted. There's no such thing as a "global user". You're either a `GlobalAdmin` or you're a user on an application.

**Comment by mrvisser** [comment]
Implemented as part of https://github.com/fronteerio/grasshopper/pull/90
