### ISSUE TITLE
Rollover API

### ISSUE THREAD

**Issue by simong** [fronteerio/grasshopper#72]
A dedicated REST API endpoint will be developed to assist in the yearly rollover of Timetable data to the new academic year. This endpoint will be responsible for calculating the offset of each event and converting the data of the event to the new academic year. The endpoint will also be responsible for creating the user accounts for all organisers associated to the rolled over events.

The rollover REST API should be available to application administrators only.

**Comment by nicolaasmatthijs** [comment]
Should this be closed in favour of #75 ?

**Comment by simong** [comment]
Yes
