### ISSUE TITLE
Importing / exporting data for an organisational unit

### ISSUE THREAD

**Issue by nicolaasmatthijs** [fronteerio/grasshopper#73]
**Endpoints:**

- GET  `/api/orgunit/:id/export?type=<csv|json>`
- POST `/api/orgunit/:id/import`

**Export endpoint**

This endpoint will dump all the direct organisational units and their series/events under a specified organisational unit.

Within the TimeTable context this can be used to get the data for a specific part:

- All the modules under that part
- All the series in the modules of that part
- All the events in the series of the modules of that part

URL:

GET  `/api/orgunit/:id/export?type=json`
TODO: Define CSV format

Data:
 
```   
[
  {
    "id": 10                                                      // The module id
    "externalId": "eng-first-elec",                    // The module's external id as given to us by the engineering department
    "displayName": "Electricity",                     // The module's displayName
    "published": true,                                       // Whether the module is published to students or not
    "series": [
      {
        "id": 42,                                                // The series id
        "externalId": "eng-first-elec-01",          // The series external id as given to us by the engineering department
        "displayName": "Practicals",               // The series displayName
        "description": null,                               // The series description
        "events": [
          {
             "id":   1123,                                   // The event id in Timetable
             "externalId": "eng-first-elec-01-20150314",          //  The event id as in engineering their system
             "displayName":  "Practical",
             "description": null,
             "notes": null,
             "type": "lab",
             "start": "2014-03-14T14:00:00.000Z",
             "end": "2014-03-14T15:00:00.000Z",
             "organisers": [
               // A person who doesn't have a Cambridge Raven account but helps in running this lab / lecture / ..
               "Jack Jones",
               //  The following is a person who does have a Raven account
               {
                 "id":   523,
                 "shibbolethId":  "sg555",       // The Raven ID / Shibboleth identifier
                 "displayName": "Simon Gaeremynck",
               }
             ]
           },
           {
             "id":   1124,                                                           // The event id in Timetable
             "externalId": "eng-first-elec-01-20150321",          //  The event id as in engineering their system
             "displayName":  "Practical",
             "description": null,
             "notes": null,
             "type": "lab",
             "start": "2014-03-21T14:00:00.000Z",
             "end": "2014-03-21T15:00:00.000Z",
             "organisers": [
               "Jack Jones",            // A person who doesn't have a Cambridge Raven account but helps in running this lab / lecture / ..
               //  The following is a person who does have a Raven account
               {
                 "id":   523,
                 "shibbolethId":  "sg555",       // The Raven ID / Shibboleth identifier
                 "displayName": "Simon Gaeremynck",
               }
             ]
           },
         ]
       }
     ]
  },
  // A second module..
]
```

**Import endpoint**

This endpoint will take a set of data and ingest it into the system. It allows an application administrator to import data to a specific organisational unit. The idea is that the import API is able to take in the same data as generated by the export API. This means that users could take a dump through the export
API, manipulate it (but retain the formatting, ids, ..) and update an entire batch of modules, series and events in one go

The following would be supported:

- Creating new modules, series and/or events. If a module, serie or event has an externalId that we can't resolve to something we know about, it will be auto created
- Updating existing modules, series and/or events their metadata. Datapoints such as display names, descriptions, start/end dates, etc.. can all be updated by changing the value.

The `externalId` is the primary identifier that will be used to resolve organisational units, series and events. The `id` field will only be used when `externalId` is omitted.

Both CSV and JSON are supported.

URL:

POST  `/api/orgunit/:id/import`

Data:

See the export endpoint

**Comment by simong** [comment]
2 PRs have been submitted for this:

 - [Export logic](https://github.com/fronteerio/grasshopper/pull/96/files)
 - [Import logic](https://github.com/fronteerio/grasshopper/pull/107)
