### ISSUE TITLE
Add `event.description` into ical description

### ISSUE THREAD

**Issue by simong** [fronteerio/grasshopper#79]
A bit of an obvious oversight, but we should probably add the event description in the ical dump.
The resulting iCal description for an event should look like:
```
{{type}} with {{organiser1}}, {{organiser2}}
{{description}}

{{notes}}
```

**Comment by mrvisser** [comment]
@simong I can't find any mustache/handlebar templates ?

**Comment by simong** [comment]
That was just a way to display the structure in this ticket. The actual logic is part of `eventsToICal` in the util in gh-calendar

**Comment by mrvisser** [comment]
I see, thanks

**Comment by simong** [comment]
This has been done in https://github.com/fronteerio/grasshopper/pull/93
