### ISSUE TITLE
/api/orgunit oddity

### ISSUE THREAD

**Issue by bp323** [fronteerio/grasshopper#81]
I have 5 organisational units (module type), each with the same parent. 2 of those organisational units have event series associated with them.

When I request `/api/orgunit?app=1&includeSeries=false&parent=1112&type=module` I get the correct results: 5 organisational units without series included.

When I request `/api/orgunit?app=1&includeSeries=true&parent=1112&type=module` I get incorrect results (note the only difference being `includeSeries`). I'm expecting 5 organisational units to return, 2 of them having an Array of event series, 3 of them no event series. However, what I get is only 2 organisational units, the 2 that have event series associated to them. I would expect the 3 without event series to show up as well.

**Comment by simong** [comment]
Is this on the `borrowing` branch or on master?

**Comment by bp323** [comment]
Yeah good point, I just checked master and behaviour there is fine. it's confined to the `serie-borrow-context` branch

**Comment by nicolaasmatthijs** [comment]
I'm going to close this ticket and move the comment to that PR

**Comment by simong** [comment]
Just FYI, that branch never made it into master. We've moved to the `borrowing` branch. IIUC @Coenego has some work on this already

**Comment by nicolaasmatthijs** [comment]
Ah yes, missed that. Removed the comment from #80
